Repository embention/PDITemplates, pull requests merged in 2024-05, with the labels that each got.

#64 Updated fixed wing
  1xVeronte/Fixed_Wing/operation/ver_opdif_arctrim0.xml
  1xVeronte/Fixed_Wing/operation/ver_opdif_fmgr.xml
  1xVeronte/Fixed_Wing/operation/ver_opdif_tmcompl.xml
  1xVeronte/Fixed_Wing/operation/ver_opdif_troute.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_actions.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_blklib00.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_blklib03.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_blklib07.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_blocks.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_evact.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_events.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_limits.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_maction.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mbit.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mblocks.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mevact.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mevent.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mname.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mrvar.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_mstep.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_pdi_mode.xml
  1xVeronte/Fixed_Wing/setup/ver_spdif_tm.xml
Labels: Analysis, Commit, PDI

#65 Automatic pull request
  .github/pull_request_template.md
Labels: Analysis, CM, Comment, IT

#67 Creation of Cex2 folder
  Cex2/Minimal_Configuration/info.json
  Cex2/Minimal_Configuration/setup/cex2_spdif_arb_arb.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_arb_can.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cana.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_canb.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_cantm_c0.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_cantm_c1.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_cantm_c2.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_cantm_p0.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_cantm_p1.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_cantm_p2.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx2_pccan.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_arb.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_base.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_can_fmset.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_canin.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_canou.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_cansc.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_ecaps.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_fmset.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_fmsgc.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_fmsgp.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_gpio.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_jetbx.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_lift.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_pceca.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_pcu8.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_ppm.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_pps.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_pulse.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_cx_pwm.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_hi_3210_rx.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_hi_3210_tx.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_i2cdevs.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_ports.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_scia.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_scib.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_scic.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_status.xml
  Cex2/Minimal_Configuration/setup/cex2_spdif_tunnel.xml
  Cex2/README.md
Labels: Artifact, Commit, PDI

#68 CEX2 image modified
  Cex2/Minimal_Configuration/info.json
Labels: Artifact, Commit, PDI

#69 Automatic pull request
  .github/pull_request_template.md
Labels: CM, Commit, Doc, Quality, Procedure
